language: python
python: "3.7"
env:
  - TOXENV=py27
  - TOXENV=py37
  - TOXENV=lint
matrix:
  include:
  - python: "3.5"
    env: TOXENV=py35
  - python: "3.6"
    env: TOXENV=py36
install:
  - pip install tox coveralls
script: tox
after_success:
  if [ "$TOXENV" == "py37" ]; then coveralls; fi
